language: rust
cache: cargo
env:
  - TEST_DIR=2017/day_1
  - TEST_DIR=2017/day_2
  - TEST_DIR=2017/day_3
  - TEST_DIR=2017/day_4
  - TEST_DIR=2017/day_5
  - TEST_DIR=2017/day_6
  - TEST_DIR=2017/day_8
  - TEST_DIR=2017/day_12
script: cd $TEST_DIR && cargo test --verbose --all 
